#!/bin/bash
cd src/greatappxyz/authorization-service
title='Authorization Service'
echo -n -e "\033]0;$title\007"
sh gradlew build -x test
java -jar build/libs/authorization-service-0.0.1-SNAPSHOT.jar